Add support for GME (Game Music Emulator)

diff --git a/configure b/configure
--- a/configure
+++ b/configure
@@ -793,6 +793,8 @@ VORBIS_LIBS
 VORBIS_CFLAGS
 TREMOR_LIBS
 TREMOR_CFLAGS
+GME_LIBS
+GME_CFLAGS
 FLUIDSYNTH_LIBS
 FLUIDSYNTH_CFLAGS
 LIBMIKMOD_CONFIG
@@ -931,6 +933,8 @@ with_timidity_cfg
 enable_music_midi_native
 enable_music_midi_fluidsynth
 enable_music_midi_fluidsynth_shared
+enable_music_gme
+enable_music_gme_shared
 enable_music_ogg
 enable_music_ogg_tremor
 enable_music_ogg_shared
@@ -968,6 +972,8 @@ XMP_CFLAGS
 XMP_LIBS
 FLUIDSYNTH_CFLAGS
 FLUIDSYNTH_LIBS
+GME_CFLAGS
+GME_LIBS
 TREMOR_CFLAGS
 TREMOR_LIBS
 VORBIS_CFLAGS
@@ -1622,6 +1628,9 @@ Optional Features:
                           enable FluidSynth MIDI output [default=yes]
   --enable-music-midi-fluidsynth-shared
                           dynamically load FluidSynth library [default=yes]
+  --enable-music-gme      enable GME music [default=no]
+  --enable-music-gme-shared
+                          dynamically load libgme library [default=yes]
   --enable-music-ogg      enable Ogg Vorbis music [default=yes]
   --enable-music-ogg-tremor
                           enable OGG Vorbis music via libtremor [default=no]
@@ -1683,6 +1692,8 @@ Some influential environment variables:
               C compiler flags for FLUIDSYNTH, overriding pkg-config
   FLUIDSYNTH_LIBS
               linker flags for FLUIDSYNTH, overriding pkg-config
+  GME_CFLAGS  C compiler flags for GME, overriding pkg-config
+  GME_LIBS    linker flags for GME, overriding pkg-config
   TREMOR_CFLAGS
               C compiler flags for TREMOR, overriding pkg-config
   TREMOR_LIBS linker flags for TREMOR, overriding pkg-config
@@ -4122,13 +4133,13 @@ if ${lt_cv_nm_interface+:} false; then :
 else
   lt_cv_nm_interface="BSD nm"
   echo "int some_variable = 0;" > conftest.$ac_ext
-  (eval echo "\"\$as_me:4125: $ac_compile\"" >&5)
+  (eval echo "\"\$as_me:4136: $ac_compile\"" >&5)
   (eval "$ac_compile" 2>conftest.err)
   cat conftest.err >&5
-  (eval echo "\"\$as_me:4128: $NM \\\"conftest.$ac_objext\\\"\"" >&5)
+  (eval echo "\"\$as_me:4139: $NM \\\"conftest.$ac_objext\\\"\"" >&5)
   (eval "$NM \"conftest.$ac_objext\"" 2>conftest.err > conftest.out)
   cat conftest.err >&5
-  (eval echo "\"\$as_me:4131: output\"" >&5)
+  (eval echo "\"\$as_me:4142: output\"" >&5)
   cat conftest.out >&5
   if $GREP 'External.*some_variable' conftest.out > /dev/null; then
     lt_cv_nm_interface="MS dumpbin"
@@ -5342,7 +5353,7 @@ ia64-*-hpux*)
   ;;
 *-*-irix6*)
   # Find out which ABI we are using.
-  echo '#line 5345 "configure"' > conftest.$ac_ext
+  echo '#line 5356 "configure"' > conftest.$ac_ext
   if { { eval echo "\"\$as_me\":${as_lineno-$LINENO}: \"$ac_compile\""; } >&5
   (eval $ac_compile) 2>&5
   ac_status=$?
@@ -7167,11 +7178,11 @@ else
    -e 's:.*FLAGS}\{0,1\} :&$lt_compiler_flag :; t' \
    -e 's: [^ ]*conftest\.: $lt_compiler_flag&:; t' \
    -e 's:$: $lt_compiler_flag:'`
-   (eval echo "\"\$as_me:7170: $lt_compile\"" >&5)
+   (eval echo "\"\$as_me:7181: $lt_compile\"" >&5)
    (eval "$lt_compile" 2>conftest.err)
    ac_status=$?
    cat conftest.err >&5
-   echo "$as_me:7174: \$? = $ac_status" >&5
+   echo "$as_me:7185: \$? = $ac_status" >&5
    if (exit $ac_status) && test -s "$ac_outfile"; then
      # The compiler can only warn and ignore the option if not recognized
      # So say no if there are warnings other than the usual output.
@@ -7516,11 +7527,11 @@ else
    -e 's:.*FLAGS}\{0,1\} :&$lt_compiler_flag :; t' \
    -e 's: [^ ]*conftest\.: $lt_compiler_flag&:; t' \
    -e 's:$: $lt_compiler_flag:'`
-   (eval echo "\"\$as_me:7519: $lt_compile\"" >&5)
+   (eval echo "\"\$as_me:7530: $lt_compile\"" >&5)
    (eval "$lt_compile" 2>conftest.err)
    ac_status=$?
    cat conftest.err >&5
-   echo "$as_me:7523: \$? = $ac_status" >&5
+   echo "$as_me:7534: \$? = $ac_status" >&5
    if (exit $ac_status) && test -s "$ac_outfile"; then
      # The compiler can only warn and ignore the option if not recognized
      # So say no if there are warnings other than the usual output.
@@ -7621,11 +7632,11 @@ else
    -e 's:.*FLAGS}\{0,1\} :&$lt_compiler_flag :; t' \
    -e 's: [^ ]*conftest\.: $lt_compiler_flag&:; t' \
    -e 's:$: $lt_compiler_flag:'`
-   (eval echo "\"\$as_me:7624: $lt_compile\"" >&5)
+   (eval echo "\"\$as_me:7635: $lt_compile\"" >&5)
    (eval "$lt_compile" 2>out/conftest.err)
    ac_status=$?
    cat out/conftest.err >&5
-   echo "$as_me:7628: \$? = $ac_status" >&5
+   echo "$as_me:7639: \$? = $ac_status" >&5
    if (exit $ac_status) && test -s out/conftest2.$ac_objext
    then
      # The compiler can only warn and ignore the option if not recognized
@@ -7676,11 +7687,11 @@ else
    -e 's:.*FLAGS}\{0,1\} :&$lt_compiler_flag :; t' \
    -e 's: [^ ]*conftest\.: $lt_compiler_flag&:; t' \
    -e 's:$: $lt_compiler_flag:'`
-   (eval echo "\"\$as_me:7679: $lt_compile\"" >&5)
+   (eval echo "\"\$as_me:7690: $lt_compile\"" >&5)
    (eval "$lt_compile" 2>out/conftest.err)
    ac_status=$?
    cat out/conftest.err >&5
-   echo "$as_me:7683: \$? = $ac_status" >&5
+   echo "$as_me:7694: \$? = $ac_status" >&5
    if (exit $ac_status) && test -s out/conftest2.$ac_objext
    then
      # The compiler can only warn and ignore the option if not recognized
@@ -10111,7 +10122,7 @@ else
   lt_dlunknown=0; lt_dlno_uscore=1; lt_dlneed_uscore=2
   lt_status=$lt_dlunknown
   cat > conftest.$ac_ext <<_LT_EOF
-#line 10114 "configure"
+#line 10125 "configure"
 #include "confdefs.h"
 
 #if HAVE_DLFCN_H
@@ -10207,7 +10218,7 @@ else
   lt_dlunknown=0; lt_dlno_uscore=1; lt_dlneed_uscore=2
   lt_status=$lt_dlunknown
   cat > conftest.$ac_ext <<_LT_EOF
-#line 10210 "configure"
+#line 10221 "configure"
 #include "confdefs.h"
 
 #if HAVE_DLFCN_H
@@ -13425,11 +13436,11 @@ else
    -e 's:.*FLAGS}\{0,1\} :&$lt_compiler_flag :; t' \
    -e 's: [^ ]*conftest\.: $lt_compiler_flag&:; t' \
    -e 's:$: $lt_compiler_flag:'`
-   (eval echo "\"\$as_me:13428: $lt_compile\"" >&5)
+   (eval echo "\"\$as_me:13439: $lt_compile\"" >&5)
    (eval "$lt_compile" 2>conftest.err)
    ac_status=$?
    cat conftest.err >&5
-   echo "$as_me:13432: \$? = $ac_status" >&5
+   echo "$as_me:13443: \$? = $ac_status" >&5
    if (exit $ac_status) && test -s "$ac_outfile"; then
      # The compiler can only warn and ignore the option if not recognized
      # So say no if there are warnings other than the usual output.
@@ -13524,11 +13535,11 @@ else
    -e 's:.*FLAGS}\{0,1\} :&$lt_compiler_flag :; t' \
    -e 's: [^ ]*conftest\.: $lt_compiler_flag&:; t' \
    -e 's:$: $lt_compiler_flag:'`
-   (eval echo "\"\$as_me:13527: $lt_compile\"" >&5)
+   (eval echo "\"\$as_me:13538: $lt_compile\"" >&5)
    (eval "$lt_compile" 2>out/conftest.err)
    ac_status=$?
    cat out/conftest.err >&5
-   echo "$as_me:13531: \$? = $ac_status" >&5
+   echo "$as_me:13542: \$? = $ac_status" >&5
    if (exit $ac_status) && test -s out/conftest2.$ac_objext
    then
      # The compiler can only warn and ignore the option if not recognized
@@ -13576,11 +13587,11 @@ else
    -e 's:.*FLAGS}\{0,1\} :&$lt_compiler_flag :; t' \
    -e 's: [^ ]*conftest\.: $lt_compiler_flag&:; t' \
    -e 's:$: $lt_compiler_flag:'`
-   (eval echo "\"\$as_me:13579: $lt_compile\"" >&5)
+   (eval echo "\"\$as_me:13590: $lt_compile\"" >&5)
    (eval "$lt_compile" 2>out/conftest.err)
    ac_status=$?
    cat out/conftest.err >&5
-   echo "$as_me:13583: \$? = $ac_status" >&5
+   echo "$as_me:13594: \$? = $ac_status" >&5
    if (exit $ac_status) && test -s out/conftest2.$ac_objext
    then
      # The compiler can only warn and ignore the option if not recognized
@@ -16587,6 +16598,227 @@ if test x$enable_music_midi_timidity != xyes -a \
         x$have_fluidsynth != xyes; then
     { $as_echo "$as_me:${as_lineno-$LINENO}: WARNING: MIDI support disabled" >&5
 $as_echo "$as_me: WARNING: MIDI support disabled" >&2;}
+fi
+
+if test x$enable_music_midi_timidity != xyes -a \
+        x$use_music_midi_native != xyes -a x$use_music_midi_native != xyes_cpp -a \
+        x$have_fluidsynth != xyes; then
+    { $as_echo "$as_me:${as_lineno-$LINENO}: WARNING: MIDI support disabled" >&5
+$as_echo "$as_me: WARNING: MIDI support disabled" >&2;}
+fi
+
+# Check whether --enable-music-gme was given.
+if test "${enable_music_gme+set}" = set; then :
+  enableval=$enable_music_gme;
+else
+  enable_music_gme=no
+fi
+
+# Check whether --enable-music-gme-shared was given.
+if test "${enable_music_gme_shared+set}" = set; then :
+  enableval=$enable_music_gme_shared;
+else
+  enable_music_gme_shared=yes
+fi
+
+if test x$enable_music_gme = xyes; then
+
+pkg_failed=no
+{ $as_echo "$as_me:${as_lineno-$LINENO}: checking for libgme" >&5
+$as_echo_n "checking for libgme... " >&6; }
+
+if test -n "$GME_CFLAGS"; then
+    pkg_cv_GME_CFLAGS="$GME_CFLAGS"
+ elif test -n "$PKG_CONFIG"; then
+    if test -n "$PKG_CONFIG" && \
+    { { $as_echo "$as_me:${as_lineno-$LINENO}: \$PKG_CONFIG --exists --print-errors \"libgme\""; } >&5
+  ($PKG_CONFIG --exists --print-errors "libgme") 2>&5
+  ac_status=$?
+  $as_echo "$as_me:${as_lineno-$LINENO}: \$? = $ac_status" >&5
+  test $ac_status = 0; }; then
+  pkg_cv_GME_CFLAGS=`$PKG_CONFIG --cflags "libgme" 2>/dev/null`
+		      test "x$?" != "x0" && pkg_failed=yes
+else
+  pkg_failed=yes
+fi
+ else
+    pkg_failed=untried
+fi
+if test -n "$GME_LIBS"; then
+    pkg_cv_GME_LIBS="$GME_LIBS"
+ elif test -n "$PKG_CONFIG"; then
+    if test -n "$PKG_CONFIG" && \
+    { { $as_echo "$as_me:${as_lineno-$LINENO}: \$PKG_CONFIG --exists --print-errors \"libgme\""; } >&5
+  ($PKG_CONFIG --exists --print-errors "libgme") 2>&5
+  ac_status=$?
+  $as_echo "$as_me:${as_lineno-$LINENO}: \$? = $ac_status" >&5
+  test $ac_status = 0; }; then
+  pkg_cv_GME_LIBS=`$PKG_CONFIG --libs "libgme" 2>/dev/null`
+		      test "x$?" != "x0" && pkg_failed=yes
+else
+  pkg_failed=yes
+fi
+ else
+    pkg_failed=untried
+fi
+
+
+
+if test $pkg_failed = yes; then
+        { $as_echo "$as_me:${as_lineno-$LINENO}: result: no" >&5
+$as_echo "no" >&6; }
+
+if $PKG_CONFIG --atleast-pkgconfig-version 0.20; then
+        _pkg_short_errors_supported=yes
+else
+        _pkg_short_errors_supported=no
+fi
+        if test $_pkg_short_errors_supported = yes; then
+	        GME_PKG_ERRORS=`$PKG_CONFIG --short-errors --print-errors --cflags --libs "libgme" 2>&1`
+        else
+	        GME_PKG_ERRORS=`$PKG_CONFIG --print-errors --cflags --libs "libgme" 2>&1`
+        fi
+	# Put the nasty error message in config.log where it belongs
+	echo "$GME_PKG_ERRORS" >&5
+
+	            ac_fn_c_check_header_mongrel "$LINENO" "gme/gme.h" "ac_cv_header_gme_gme_h" "$ac_includes_default"
+if test "x$ac_cv_header_gme_gme_h" = xyes; then :
+  have_gme_hdr=yes
+fi
+
+
+            { $as_echo "$as_me:${as_lineno-$LINENO}: checking for gme_open_data in -lgme" >&5
+$as_echo_n "checking for gme_open_data in -lgme... " >&6; }
+if ${ac_cv_lib_gme_gme_open_data+:} false; then :
+  $as_echo_n "(cached) " >&6
+else
+  ac_check_lib_save_LIBS=$LIBS
+LIBS="-lgme  $LIBS"
+cat confdefs.h - <<_ACEOF >conftest.$ac_ext
+/* end confdefs.h.  */
+
+/* Override any GCC internal prototype to avoid an error.
+   Use char because int might match the return type of a GCC
+   builtin and then its argument prototype would still apply.  */
+#ifdef __cplusplus
+extern "C"
+#endif
+char gme_open_data ();
+int
+main ()
+{
+return gme_open_data ();
+  ;
+  return 0;
+}
+_ACEOF
+if ac_fn_c_try_link "$LINENO"; then :
+  ac_cv_lib_gme_gme_open_data=yes
+else
+  ac_cv_lib_gme_gme_open_data=no
+fi
+rm -f core conftest.err conftest.$ac_objext \
+    conftest$ac_exeext conftest.$ac_ext
+LIBS=$ac_check_lib_save_LIBS
+fi
+{ $as_echo "$as_me:${as_lineno-$LINENO}: result: $ac_cv_lib_gme_gme_open_data" >&5
+$as_echo "$ac_cv_lib_gme_gme_open_data" >&6; }
+if test "x$ac_cv_lib_gme_gme_open_data" = xyes; then :
+  have_gme_lib=yes;GME_LIBS="-lgme"
+fi
+
+
+elif test $pkg_failed = untried; then
+        { $as_echo "$as_me:${as_lineno-$LINENO}: result: no" >&5
+$as_echo "no" >&6; }
+	            ac_fn_c_check_header_mongrel "$LINENO" "gme/gme.h" "ac_cv_header_gme_gme_h" "$ac_includes_default"
+if test "x$ac_cv_header_gme_gme_h" = xyes; then :
+  have_gme_hdr=yes
+fi
+
+
+            { $as_echo "$as_me:${as_lineno-$LINENO}: checking for gme_open_data in -lgme" >&5
+$as_echo_n "checking for gme_open_data in -lgme... " >&6; }
+if ${ac_cv_lib_gme_gme_open_data+:} false; then :
+  $as_echo_n "(cached) " >&6
+else
+  ac_check_lib_save_LIBS=$LIBS
+LIBS="-lgme  $LIBS"
+cat confdefs.h - <<_ACEOF >conftest.$ac_ext
+/* end confdefs.h.  */
+
+/* Override any GCC internal prototype to avoid an error.
+   Use char because int might match the return type of a GCC
+   builtin and then its argument prototype would still apply.  */
+#ifdef __cplusplus
+extern "C"
+#endif
+char gme_open_data ();
+int
+main ()
+{
+return gme_open_data ();
+  ;
+  return 0;
+}
+_ACEOF
+if ac_fn_c_try_link "$LINENO"; then :
+  ac_cv_lib_gme_gme_open_data=yes
+else
+  ac_cv_lib_gme_gme_open_data=no
+fi
+rm -f core conftest.err conftest.$ac_objext \
+    conftest$ac_exeext conftest.$ac_ext
+LIBS=$ac_check_lib_save_LIBS
+fi
+{ $as_echo "$as_me:${as_lineno-$LINENO}: result: $ac_cv_lib_gme_gme_open_data" >&5
+$as_echo "$ac_cv_lib_gme_gme_open_data" >&6; }
+if test "x$ac_cv_lib_gme_gme_open_data" = xyes; then :
+  have_gme_lib=yes;GME_LIBS="-lgme"
+fi
+
+
+else
+	GME_CFLAGS=$pkg_cv_GME_CFLAGS
+	GME_LIBS=$pkg_cv_GME_LIBS
+        { $as_echo "$as_me:${as_lineno-$LINENO}: result: yes" >&5
+$as_echo "yes" >&6; }
+	            have_gme_hdr=yes
+            have_gme_lib=yes
+            have_gme_pc=yes
+
+fi
+    if test x$have_gme_hdr = xyes -a x$have_gme_lib = xyes; then
+        have_gme=yes
+        case "$host" in
+            *-*-darwin*)
+                gme_lib=`find_lib libgme.dylib`
+                ;;
+            *-*-cygwin* | *-*-mingw*)
+                gme_lib=`find_lib "libgme*.dll"`
+                ;;
+            *)
+                gme_lib=`find_lib "libgme.so.*"`
+                ;;
+        esac
+        EXTRA_CFLAGS="$EXTRA_CFLAGS -DMUSIC_GME $GME_CFLAGS"
+        if test x$enable_music_gme_shared = xyes && test x$gme_lib != x; then
+            echo "-- dynamic libgme -> $gme_lib"
+            EXTRA_CFLAGS="$EXTRA_CFLAGS -DGME_DYNAMIC=\\\"$gme_lib\\\""
+        else
+            EXTRA_LDFLAGS="$EXTRA_LDFLAGS $GME_LIBS"
+            if test x$have_gme_pc = xyes; then
+                PC_REQUIRES="$PC_REQUIRES libgme"
+            else
+                PC_LIBS="$PC_LIBS $GME_LIBS"
+            fi
+        fi
+    else
+        { $as_echo "$as_me:${as_lineno-$LINENO}: WARNING: *** Unable to find GME library" >&5
+$as_echo "$as_me: WARNING: *** Unable to find GME library" >&2;}
+        { $as_echo "$as_me:${as_lineno-$LINENO}: WARNING: GME support disabled" >&5
+$as_echo "$as_me: WARNING: GME support disabled" >&2;}
+    fi
 fi
 
 # Check whether --enable-music-ogg was given.
